# istio-static image is prebuilt with 1337:1337.
# https://github.com/istio/distroless/tree/iptables/istio
FROM gcr.io/istio-release/distroless/istio-static@sha256:dd0c6ee10e7bbed693546d43d256863412a5c95f2a786f744684b8ccc48496a8 as distroless_source